packages:
  - "apps/*"
  - "packages/*"
  - "configs/**"
  - "!**/test/**"

minimumReleaseAge: 10080
blockExoticSubdeps: true
strictDepBuilds: true

onlyBuiltDependencies:
  - esbuild

minimumReleaseAgeExclude:
  - "@changesets/cli@3.0.1"
  - "@changesets/write@1.0.1"

allowBuilds:
  esbuild: true
