name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v6

      - name: 🦆 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 🛠️ Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org"

      - name: 📦 Install deps
        run: pnpm install --frozen-lockfile

      - name: 🗂️ Setup turbo cache
        uses: rharkor/caching-for-turbo@v1.8

      - name: 🧾 Create release PR or publish
        uses: changesets/action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-script: pnpm release
          create-github-releases: true
          push-with-git-cli: true
